### ISSUE TITLE
Golden hero portraits messing with hero selection

### ISSUE THREAD

**Issue by mrapp** [rembound/Arena-Helper#13]
The new patch allows us to use golden hero portraits in Arena. I believe this is causing an issue where Arena Helper does not recognize the hero selection screen. The Arena Helper window is stuck on the "Detecting heroes..." dialog.

**Comment by rembound** [comment]
I don't have the visual hashes for the golden heroes and the new heroes yet. If you enable the debug mode and take screenshots of the scenes I describe below, I might be able to see the new hashes.
>You can enable some on-screen debug information by going to the AppData directory: >HearthstoneDeckTracker\ArenaHelper\ opening arenahelper.json and modifying: "debug": true

Another thing you and others could do, is take a couple of screenshots using the following method:
1) Set your resolution to 1280x960, in window mode.
2) Take screenshots with Print-Screen, the files will appear on your desktop. The screenshots should be in the lossless .png format.

I will need screenshots of the following scenes:
Heroes:
![hearthstone screenshot 05-31-15 13 38 16](https://cloud.githubusercontent.com/assets/11648276/8183975/f09a4562-143b-11e5-91ab-570db8bc5e7d.png)

Selected Hero:
![hearthstone screenshot 05-31-15 13 49 55](https://cloud.githubusercontent.com/assets/11648276/8183982/f7ca9bac-143b-11e5-8bed-da2618d76b32.png)

I don't know if this will be enough, because the golden portraits have animations.

**Comment by rembound** [comment]
In the next version, I will add a manual hero selection override. This also allows players to use the plugin, even if they already selected a hero.

Work in progress:
![configurehero](https://cloud.githubusercontent.com/assets/11648276/8192514/fea20d10-146e-11e5-9728-0cc637437662.png)

**Comment by mrapp** [comment]
Thanks for the info, I only have a golden warrior but I will try and take some screen shots next time it comes up.

**Comment by rembound** [comment]
I will make a new issue and close this one.
