### ISSUE TITLE
[Plugin Feature Request] Ability to return the highest card values

### ISSUE THREAD

**Issue by GeKopt** [rembound/Arena-Helper#155]
Hey,

I'm trying to write a plugin to the Arena Helper.
But when i want to show the default + custom values, i can't guarantee that i will have the correct card highlighted.
That is because all the numbers in te value string are combined to form 1 number. And based on number the highlighted card is determined.

So for example, where i would get a weird highlight. 

Following Card Scores + total value
Default score = 60, My score = 80 Total = 6080
Default score = 50, My score = 90 Total = 5090
Default score = 100, My score = 60 Total = 10060

This would mean the 10060 will be highlighted instead of the 5090

Would it be possible to give us something so that we could give the numeric values of the scores ourself? and thus being able to show more stuff but still give an accurate highlight? Or that we can set the highlighted card ourselves?

Gr GeKopt

**Comment by rembound** [comment]
There is already some support to add custom messages, check out: https://github.com/rembound/Arena-Helper/issues/18

It allows to return a correct value, and it ignores everything after the first space, for example:
`80 Default: 60`

The message after `80` gets ignored in the calculation because of the space character, other special characters are stripped to form a correct number.

**Comment by GeKopt** [comment]
Ah yes. I can see it in the first lines of the GetNumericalValue. guess i just wasn't looking...  :(
