### ISSUE TITLE
Arena Helper mistakenly detect Demon Hunter as Paladin

### ISSUE THREAD

**Issue by minhngoc25a** [rembound/Arena-Helper#168]
![image](https://user-images.githubusercontent.com/33834488/90983611-a9d09e80-e599-11ea-9c14-495e07a6ddc2.png)

After I started an Arena run, the plugin had mistakenly detected the Illidan hero as Paladin.

**Comment by swilkins1337** [comment]
I noticed myself, but I didn't take a screenshot at the time, otherwise I might've reported it. Anyway, I did some digging, and it looks like HDT returns "DemonHunter" and Arena Helper is expecting "Demon Hunter". You could fix Plugin.cs:245, but I'm pretty sure that would cause it to render as "DemonHunter" in the UI. Maybe the bug should be kicked upstream to HDT?

**Comment by rembound** [comment]
Thanks for the bug report.
Added a fix in v0.9.5, but couldn't test it properly yet.
