### ISSUE TITLE
Chosen cards not recognized correctly.

### ISSUE THREAD

**Issue by n4ru** [rembound/Arena-Helper#3]
As title states. I go through the process normally, but after saving the deck it comes out horribly wrong. Probably at least HALF of the cards were NOT the ones I chose. Guessing it's an OCR issue.

**Comment by rembound** [comment]
It is not an OCR issue. Plugins get updated every 100 ms by Hearthstone Deck Tracker. I can't use the mousehook method to detect mouse clicks, because it slows down everything. I use GetAsyncKeyState. If your fps is low there could be a delay in registering mouse clicks. Try to click on cards slowly, using a single click, and wait with moving the mouse off the cards, until the next set of cards are detected. Don't click on anything else, after clicking a card.

**Comment by Epix37** [comment]
Instead of checking for actual clicks, have you tried visually checking for a card being picked? (something like [this](https://camo.githubusercontent.com/4c968f0dc8c6a9dfc1e0d7d708f6b23a1a6f1a1f/687474703a2f2f692e696d6775722e636f6d2f5368664d5a6e772e706e67) or maybe just a new set of cards).

Or anything I could do to make this more reliable? More frequent OnUpdate calls?

**Comment by rembound** [comment]
There is no reliable visual clue I can use to check which card was picked. The list of cards on the right side of the screen scrolls when it becomes larger. Using OCR techniques on this list is not reliable. Maybe if plugins have direct access to mousehook events.. If I add my own mousehook, everything stutters, because of the 100ms update timer. The plugin thread gets suspended for a time. I don't think more frequent updates are the solution. The 100ms updates already works reliably on my computer, but I don't know the effect on slower computers.

**Comment by rembound** [comment]
I added a manual card selection option. If automatic detection doesn't work, you can enable manual selection. For this to work, you should select the card in Hearthstone first, afterwards you can select the card in the Arena Helper window.

**Comment by culinko** [comment]
Not sure if you got this solved already, but Arena logger (Arena.log) already shows you which card was picked.

**Comment by rembound** [comment]
Thanks for the suggestion. I'm currently still using click detection, but I know the card picks show up in the logs recently. Maybe in a future version, if it is reliable.
