### ISSUE TITLE
Wrong card detection, after update.

### ISSUE THREAD

**Issue by chimzuk** [rembound/Arena-Helper#42]
After the todays Decktracker update Arena Helper plugin started to mess up with the card detection.
Came to inform you, hope it will be an easy fix for you. 
(downgrade helped for now)
When i got an update of DeckTracker and go to arena, it detects two cards right, and the one of them shows as a card from the new adventure, but it is not of cource.

**Comment by rembound** [comment]
It could be that some new cards are visually similar to other cards. Try to increase the resolution of your Hearthstone window. Lower resolutions will mess with the detection.

**Comment by chimzuk** [comment]
I played in Fullscreen 1920*1200 =)
I have no accec to arena now, but as it was last time, it used to make the mistakes only with a middle card of three. And i think it's not a visual problem, if i correctly recall, it preposed me Obsidian destroyer instead the creeper. You should definitly check it by yourself.
http://media-hearth.cursecdn.com/avatars/270/977/635824316649839182.png
http://cdn.pcgamesn.com/sites/default/files/HauntedCreeper.jpg

**Comment by rembound** [comment]
In my tests all cards were detected as normal. I even had a Haunted Creeper in my deck. I think this problem can always occur in certain situations, because detection is based on taking a screenshot and calculating a hash value using the screen pixels. Unfortunately there is no fix as there will always be an error rate.

If it occurs again, you can try to enable the debug mode. It will tell you some info about the detected cards.

**Comment by chimzuk** [comment]
Ok i will try to catch this problem if it occurs. 
Never happend any errors for me before this update =)

**Comment by bazukamos** [comment]
Good night,
I'm having the same problem, i was able to get a "full" screenshot in window mode (since i only play in full screen) and this is what's happening:
http://postimg.org/image/wndqmzw8f/
By the way, this is from a clean install.
Dunno if it is a "general bug" or just in a few users, but hope this info can help out solving the problem (if there is any...)
Thanks for your time, and keep the good job.

**Comment by rembound** [comment]
Thanks for the report.

**Comment by gabrielhpugliese** [comment]
Same here (1080p):
![image](https://cloud.githubusercontent.com/assets/1252818/11171940/1699c024-8be4-11e5-880f-b8b3affff8fc.png)

**Comment by chimzuk** [comment]
Interesting moment. Updated 0.6.0
Now it detects cards right in debug, but still shows the wrong card.
![image](https://cloud.githubusercontent.com/assets/12091461/11181156/b0a32dca-8c68-11e5-9199-450adfe15754.png)
http://i.imgur.com/UDfOe7U.jpg

**Comment by rembound** [comment]
Maybe it detected the wrong card during a transition animation, if the animation was long enough on the screen due to a slowdown or bad performance.

The plugin needs to detect the cards multiple times in a row, multiple confirmations, and then decides that it is the right card. The debug mode shows the raw detection information.
