### ISSUE TITLE
New release needed?

### ISSUE THREAD

**Issue by ubloh** [rembound/Arena-Helper#71]
The tier list has been updated and you made the according commits.
However, there is no new release and my local tier list and version file hasn't changed...
Is it normal?

(Great job on this program btw :D)

**Comment by rembound** [comment]
In the latest version of the plugin, the tier list and other data files are getting auto-updated, but they don't write the files to the "Program Files" directory anymore because of file permission issues on some systems. The updated data files are downloaded to the %appdata% HDT directory. This means that the plugin directory contains the initial data files, but it uses the updated files if they can be found. After an auto-update, the plugin always displays a message that the files were updated.

You can check if you have the latest files by going to the `%APPDATA%\HearthstoneDeckTracker\ArenaHelper\Data` directory.

Thanks :)

**Comment by ubloh** [comment]
That's right, I remember now there was a change regarding auto-updates...
So, I still checked and everything is in order in my appdata directory.

Thanks for your quick response!
