### ISSUE TITLE
Having problems with Arena-Helper recognizing my heroes

### ISSUE THREAD

**Issue by mongstradamus** [rembound/Arena-Helper#78]
I have installed everything according to the directions. I am not sure if I am missing something, when I run in debug mode the only thing that shows up is an messaged in the upper left hand corner of the screen saying arenacheckl:30. Arena Helper plugin just shows detecting arena , thats as far as i can get. 
![arena-helper](https://cloud.githubusercontent.com/assets/18374318/14408212/ac60d236-feb8-11e5-8434-c4d8a80b3419.jpg)

**Comment by rembound** [comment]
Try changing the resolution and/or aspect ratio. Arenacheck should be below 10.

**Comment by mongstradamus** [comment]
I tried every possible resolution setting in hearthstone , and the arena check number still stays at the same number. I am pretty sure i am using all the standard windows modes. Only have one monitor setup.

**Comment by rembound** [comment]
The missing dll is normal, so that is not the problem.

Something is preventing the window from being captured, some other functions of Hearthstone Deck Tracker also rely on it I think. Try changing from fullscreen to windowed or make it borderless or remove borderless. You can make the HS window borderless by using the info in this reddit post: [Borderless](https://www.reddit.com/r/hearthstone/comments/2vab8d/hearthstone_needs_a_borderless_setting_for_all/cofydew)

Maybe some other program on your computer is preventing the window from being captured..

**Comment by mongstradamus** [comment]
I have tried all your suggestions I guess it just doesn't work my computer setup that's unfortunate. I don't know if it matter but other parts of hearthstone deck tracker work just not the arena helper plugin.

**Comment by rembound** [comment]
Only a few functions of HDT use screen capturing, it will not interfere with the main functionality of deck tracker. Unfortunately, I don't have a solution. Some other suggestions: Run as admin, disable virus scan
