### ISSUE TITLE
Arena Helper crashing

### ISSUE THREAD

**Issue by fmoraes74** [rembound/Arena-Helper#95]
Arena Helper has been causing HDT to while drafting a deck. Attached are two logs.

[Crash report 2672016-197.txt](https://github.com/rembound/Arena-Helper/files/387463/Crash.report.2672016-197.txt)
[Crash report 2072016-2028.txt](https://github.com/rembound/Arena-Helper/files/387464/Crash.report.2072016-2028.txt)

**Comment by rembound** [comment]
Thanks for the report, it looks like it crashes because of the HA plugin.
Disable the HDTAHPluginHAPlugin, by removing the dll from the `ArenaHelper\plugins` directory.

The HA plugin hasn't been updated in a while, see: https://github.com/corlettb/HDTAHPluginHAPlugin/issues/6
To make it work, you can try: https://github.com/corlettb/HDTAHPluginHAPlugin/pull/7
